=== testConfig/seleniumSupport/seleniumSupport/XMLFolder/studentType.dtd
<!ELEMENT STUDENTS (Student+,Teacher)>
<!ELEMENT Student (Name,home,Sub)>
<!ELEMENT Teacher (Name,home,Sub)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT home (#PCDATA)>
<!ELEMENT Sub (#PCDATA)>
<!ATTLIST Student id ID #REQUIRED>
<!ATTLIST Teacher id ID  #REQUIRED>
<!ATTLIST Teacher Subject ID  #IMPLIED>

=== testConfig/seleniumSupport/seleniumSupport/XMLFolder/firstXML.xml
<!DOCTYPE STUDENTS SYSTEM "studentType.dtd">
<STUDENTS>

	<Student id="First">
		<Name>Ahammed</Name>
		<home>NY</home>
		<Sub>Science</Sub>

	</Student>
	<Student id='Second'>
		<Name>Sorif</Name>
		<home>Dhaka</home>
		<Sub>Commerce</Sub>
	</Student>
	<Teacher Subject='Math'>
		<Name>Sorif</Name>
		<home>Dhaka</home>
		<Sub>Commerce</Sub>
	</Teacher>
</STUDENTS>
